# Spicord StaffChat by Siebrenvde
# Version 1.4.7

staff-channel: "123456789012345678"

# Enabling this forces you to use -sc to send messages to the server
enable-discord-commands: false

# Enabling this will force the bot to add a reaction to the message if it has been sent to the server
enable-reactions: true

# The reaction that the bot will add to the message if it has been sent to the server
# Note: You can only use standard emojis. Custom server emojis are not supported!
success-reaction: "📨"

# ----------------------
# StaffChat
# ----------------------

# The message shown to in-game staff when using /sc in-game
# Placeholders:
# %displayname% - Displays the player's displayname
# %username% - Displays the player's username
# %message% - Displays the sent message
general-layout: "&4StaffChat &c%username%&4: &a%message%"

# The message shown to in-game staff when using -sc on Discord
# Placeholders:
# %usertag% - Displays the user's username + tag (Ex. Siebrenvde#0863)
# %username% - Displays the user's username (Ex. Siebrenvde)
# %message% - Displays the sent message
minecraft-layout: "&9Discord &4StaffChat &c%usertag%&4: &a%message%"

# The message shown in the Discord when using /sc in-game
# Placeholders:
# %displayname% - Displays the player's displayname
# %username% - Displays the player's username
# %message% - Displays the sent message
discord-layout: "**[StaffChat] %username%**: %message%"